
target "DatabaseContentCheckerExample" do
    pod "MRDatabaseContentChecker", :path => "../"
end

target "DatabaseContentCheckerExampleTests" do
    pod "MRDatabaseContentChecker", :path => "../"
end
